        
sts: local
  user: cloud
  sudo: yes

  tasks:
    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=1

    - name: system is up-to-date
      apt:
        upgrade=full

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - apache2
        - php5
      notify: start apache2
      
    - git: repo=https://github.com/aurelienmaury/cw-bundle-lamp.git
       dest=/var/www/html

    - name: common aliases
      copy:
        dest=/etc/profile.d/aliases.sh
        content="alias ll=\"ls -aul\""
        owner=root
        group=root
        mode=0644

    - name: default sh is bash
      file:
        src=/bin/bash
        dest=/bin/sh
        state=link

  handlers:
    - name: start apache2
      service:
        name=apache2
        state=restarted
        enabled=yes
