- hosts: local
  user: cloud
  sudo: yes

  tasks:

    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=1

    - name: system is up-to-date
      apt:
        upgrade=full

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - php5
        - apache2
      notify: start apache2
      notify: start php5 

    - name: common aliases
      copy:
        dest=/etc/profile.d/aliases.sh
        content="alias ll=\"ls -aul\""
        owner=root
        group=root
        mode=0644

    - name: default sh is bash
      file:
        src=/bin/bash
        dest=/bin/sh
        state=link

    - name: pip packages installed
      apt:
        name="{{ item }}"
      with_items:
        - python-glanceclient
        - python-novaclient
        - python-neutronclient
        - python-heatclient
        - python-openstackclient
        - python-cinderclient

  handlers:
    - name: start apache2
      service:
        name=apache2
        state=restarted
        enabled=yes
        
    - name: start php5
      service: start php5
        name=apache2
        state=restarted 
        enabled=yes
